language: python

python:
  - "2.7"

before_install:
  - pip install .

script:
  - python -m benchpress.testing

deploy:
  provider: pypi
  user: $TWINE_USERNAME
  password: $TWINE_PASSWORD

deploy:
  provider: script
  script:
    - pip install twine
    - python setup.py sdist
    - twine upload dist/*
  on:
    branch: master
